name: Azure Managed Pool - Basic setup test
run-name: Azure Managed Pool - Basic setup test

on:
    schedule:
        - cron: "15 06 * * 2"   # <=== Change this value    
    workflow_dispatch:
    
env:
  BadgeName: 'AzureManagedPool'
  BadgeLabel: 'AzureManagedPool'

      
jobs:
#   RunTerraform:
#     uses: ./.github/workflows/terraform-execute.yml
#     with:
#       backend_key: 'managed-pool'
#     secrets: inherit

  ValidateAPI:
    runs-on: ubuntu-latest
    # needs: RunTerraform

    steps:

      - shell: bash
        name: Trigger Azure DevOps Pipeline
        if: success()
        env:
            ADO_PAT: ${{ secrets.ADO_PAT }}
            ORGANIZATION: "azure-way"
            PROJECT: "basic-pipelines"
            PIPELINE_ID: "1"            
        run: |
            # Encode the PAT for authorization
            AUTH_HEADER=$(echo -n ":Ftk6NUy3sWGfxJGDtKTLaS17Yueu0iuUS8jCYQCqvQdbG6Z7pBh2JQQJ99BAACAAAAAAu2VXAAASAZDO2dM8" | base64)
            
            # Trigger the pipeline
            curl -v -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $AUTH_HEADER" \
            -H "Accept: application/json" \
            -d '{"resources": {"repositories": {"self": {"refName": "refs/heads/main"}}}}' \
            "https://dev.azure.com/azure-way/basic-pipelines/_apis/pipelines/1/runs?api-version=7.1"
             
            echo "Pipeline triggered successfully."
    #   - name: Get current date
    #     id: date
    #     run: echo "::set-output name=date::$(date +'%Y-%m-%d')"          

    #   - name: Build-A-Badge-Success
    #     if: success()
    #     uses: peterrhodesdev/build-a-badge@v1.3.0
    #     with:
    #         token: ${{ secrets.GITHUB_TOKEN }}
    #         filename: ${{ env.BadgeName}}
    #         label: ${{ env.BadgeLabel }}
    #         message: "build date: ${{ steps.date.outputs.date }}"
    #         namedLogo: github
    #         labelColor: "#008000"
    #         color: "#3272d3"
  
    #   - name: Build-A-Badge-Failure
    #     if: failure()
    #     uses: peterrhodesdev/build-a-badge@v1.3.0
    #     with:
    #         token: ${{ secrets.GITHUB_TOKEN }}
    #         filename: ${{ env.BadgeName}}
    #         label: ${{ env.BadgeLabel }}
    #         message: "build date: ${{ steps.date.outputs.date }}"
    #         namedLogo: github
    #         labelColor: "#FF0000"
    #         color: "#3272d3"   

#   RunDestroyTerraform:
#     needs: ValidateAPI
#     uses: ./.github/workflows/terraform-destroy.yml
#     with:
#       backend_key: 'managed-pool'
#     secrets: inherit     